#!/usr/bin/env bash
# One-shot deploy: build the SPA, bake it into the monolithic image, and
# (re)start the container with docker compose.
#
# Usage (from the repo, on the Docker host):
#   ./scripts/deploy.sh
#
# Optional env overrides:
#   IMAGE_TAG     image to build and run       (default: memos-custom:latest)
#   HOST_PORT     host port mapped to 5230     (default: 5230)
#   DATA_DIR      host dir for /var/opt/memos  (default: ~/.memos)
#
# The compose file is regenerated on every run into compose.deploy.yaml
# (gitignored), so env overrides always take effect.

set -euo pipefail

cd "$(dirname "$0")/.."

IMAGE_TAG="${IMAGE_TAG:-memos-custom:latest}"
HOST_PORT="${HOST_PORT:-5230}"
DATA_DIR="${DATA_DIR:-$HOME/.memos}"
COMPOSE_FILE="compose.deploy.yaml"
NODE_IMAGE="node:24-alpine"
PNPM_STORE_VOLUME="memos-deploy-pnpm-store"

die() {
    echo "deploy: $*" >&2
    exit 1
}

command -v docker >/dev/null 2>&1 || die "docker is not installed (or not in PATH)"
git rev-parse --short HEAD >/dev/null 2>&1 || die "not inside the git repository"

COMMIT="$(git rev-parse --short HEAD)"
VERSION="$(git describe --tags --always 2>/dev/null || echo dev)"

echo "==> Building frontend in ${NODE_IMAGE} (pnpm install + pnpm release)"
docker run --rm \
    --env COREPACK_ENABLE_DOWNLOAD_PROMPT=0 \
    --volume "$PWD":/src \
    --volume "$PNPM_STORE_VOLUME":/root/.local/share/pnpm/store \
    --workdir /src/web \
    "$NODE_IMAGE" sh -c "corepack enable pnpm && pnpm install --frozen-lockfile && pnpm release"

echo "==> Building image ${IMAGE_TAG} (version=${VERSION}, commit=${COMMIT})"
docker build \
    --file scripts/Dockerfile \
    --build-arg "VERSION=${VERSION}" \
    --build-arg "COMMIT=${COMMIT}" \
    --tag "$IMAGE_TAG" \
    .

echo "==> Regenerating ${COMPOSE_FILE} and starting the container"
mkdir -p "$DATA_DIR"
cat >"$COMPOSE_FILE" <<EOF
# Generated by scripts/deploy.sh — edit env overrides there, not here.
services:
  memos:
    image: "$IMAGE_TAG"
    container_name: memos
    restart: unless-stopped
    ports:
      - "$HOST_PORT:5230"
    volumes:
      - "$DATA_DIR":/var/opt/memos
EOF
docker compose --file "$COMPOSE_FILE" up --detach

echo "==> Deployed on port ${HOST_PORT}"
echo "    data:    ${DATA_DIR}"
echo "    logs:    docker compose --file ${COMPOSE_FILE} logs -f"